dfm1s ALPHA-FE  /d 
dfm1s ALPHA-TI  /d 
dfm1s ALPHA-ZR  /d 
dfm1s ALUMINA  /d 
dfm1s BETA-TI  /d 
dfm1s BETA-ZR  /d 
dfm1s COPPER  /d 
dfm1s LEAD  /d 
dfm1s MAGNESIA  /d 
dfm1s MAR-M200  /d 
dfm1s MOLYBDM  /d 
dfm1s NICKEL  /d 
dfm1s ROCKSALT  /d 
dfm1s SILVER  /d 
dfm1s SS-304  /d 
dfm1s SS-316  /d 
dfm1s T-STEEL  /d 
dfm1s TIN  /d 
dfm1s TUNGSTEN  /d 
dfm1s URANIA  /d 
dfm1s Y-BA-CUO  /d 
dfm1s ZIRCONIA  /d 
dpark

