Title:			DFMAP
Author:			Philip Sargent
			Cambridge University Engineering Dept.
Version:		0.88
Title From:		
Author From:	
Version From:	
Supplier:		Philip Sargent
Date:			12-June-1993 
Keywords:  Deformation modelling of metals and ceramics
Shareware:		No, GNU Public License
Machine:		IBM PC
Operating system:	DOS
Memory requirements:	about 300K
Peripherals needed:	
Other s/ware needed:	Turbo Pascal (if you wish to change anything)
Directory:		micros/ibmpc/dos/?
Date mounted/updated:	??
File names:		dfm-arc.boo
Unarchived files:	dfm-arc.arc
unarchived size:	610595 K
Omissions:		A user guide is being prepared.
See also:	

-------------------------------------------------------------------------------

Description:

DFMAP plots out the strain-rate contours over all temperatures, from 0 K
to the melting point, over a range of stresses from somethig so low as to
be equivalent to self-weight to stresses high enough such that the
deformation is limited by phonon drag.
It is an implementation of the Work of Prof. Mike F.Ashby and co-workers,
principally Harold Frost and Philip Sargent, since 1973. The original
software was several programs in Fortran, this is a rewritten and
merged package in Turbo Pascal 6.0.

NOTES
-----

To obtain the program, take the following steps:

1. Make sure you have the de-BOO utility and the PKUNPAK utility

	deboo.exe 
   pkunpak.exe

   on your disk. They are available on HENSA.

2. Download the file :

	dfm-arc.boo

   This is a BOO encoding of a compressed archive file

3. Type the command :

   deboo dfm-arc.boo

   which will produce an archive file called :

	dfm-arc.arc

4. Issue the command :

   pkunpak dfm-arc.arc

   which will produce the following files :

ATT.BGI           6348
CGA.BGI           6332
COPYING          18321
DFM.BAT            218
DFM290.EXE      140560
DFMAP.DOC          247
DFMFIX.EXE      142448
EGAVGA.BGI        5554
EXTRAS.ARC        9654
GRAPHCPQ.COM      7204
GRAPHICS.COM      3300
HELP.BAT           340
HERC.BGI          6204
HGC.COM           1618
IBM8514.BGI       6665
MAKEDIST.BAT      1898
MATLPARS.DAT     53684
MATLREFS.DAT     10623
MEMMAP.COM        9984
MEMMAP.DOC        1280
PC3270.BGI        6012
README            8501
README.BAT          20
RUNALL.BAT         499
SOURCE.ARC      146041
TEXTSORT.EXE     17040  

At this point, it would be a good idea to make up a backup copy of 
dfm-arc.arc; also at this point, you can delete the file:

	dfm-arc.boo


PLEASE NOTE 
----------- 

The source code is included in source.arc, which requires further extraction
using pkunpak. The distribution license is in the file COPYING.

