dfm1 ALPHA-FE  /d /o 
dfm1 ALPHA-TI  /d /o 
dfm1 ALPHA-ZR  /d /o 
dfm1 ALUMINA  /d /o 
dfm1 BETA-TI  /d /o 
dfm1 BETA-ZR  /d /o 
dfm1 COPPER  /d /o 
dfm1 LEAD  /d /o 
dfm1 MAGNESIA  /d /o 
dfm1 MAR-M200  /d /o 
dfm1 MOLYBDM  /d /o 
dfm1 NICKEL  /d /o 
dfm1 ROCKSALT  /d /o 
dfm1 SILVER  /d /o 
dfm1 SS-304  /d /o 
dfm1 SS-316  /d /o 
dfm1 T-STEEL  /d /o 
dfm1 TIN  /d /o 
dfm1 TUNGSTEN  /d /o 
dfm1 URANIA  /d /o 
dfm1 Y-BA-CUO  /d /o 
dfm1 ZIRCONIA  /d /o 
dpark

