dfm1s ALPHA-FE  /d /o 
dfm1s ALPHA-TI  /d /o 
dfm1s ALPHA-ZR  /d /o 
dfm1s ALUMINA  /d /o 
dfm1s BETA-TI  /d /o 
dfm1s BETA-ZR  /d /o 
dfm1s COPPER  /d /o 
dfm1s LEAD  /d /o 
dfm1s MAGNESIA  /d /o 
dfm1s MAR-M200  /d /o 
dfm1s MOLYBDM  /d /o 
dfm1s NICKEL  /d /o 
dfm1s ROCKSALT  /d /o 
dfm1s SILVER  /d /o 
dfm1s SS-304  /d /o 
dfm1s SS-316  /d /o 
dfm1s T-STEEL  /d /o 
dfm1s TIN  /d /o 
dfm1s TUNGSTEN  /d /o 
dfm1s URANIA  /d /o 
dfm1s Y-BA-CUO  /d /o 
dfm1s ZIRCONIA  /d /o 
dpark

