dfm1s ALPHA-FE  /f /w:ALPHA-FE.lst 
dfm1s ALPHA-TI  /f /w:ALPHA-TI.lst 
dfm1s ALPHA-ZR  /f /w:ALPHA-ZR.lst 
dfm1s ALUMINA  /f /w:ALUMINA.lst 
dfm1s BETA-TI  /f /w:BETA-TI.lst 
dfm1s BETA-ZR  /f /w:BETA-ZR.lst 
dfm1s COPPER  /f /w:COPPER.lst 
dfm1s LEAD  /f /w:LEAD.lst 
dfm1s MAGNESIA  /f /w:MAGNESIA.lst 
dfm1s MAR-M200  /f /w:MAR-M200.lst 
dfm1s MOLYBDM  /f /w:MOLYBDM.lst 
dfm1s NICKEL  /f /w:NICKEL.lst 
dfm1s ROCKSALT  /f /w:ROCKSALT.lst 
dfm1s SILVER  /f /w:SILVER.lst 
dfm1s SS-304  /f /w:SS-304.lst 
dfm1s SS-316  /f /w:SS-316.lst 
dfm1s T-STEEL  /f /w:T-STEEL.lst 
dfm1s TIN  /f /w:TIN.lst 
dfm1s TUNGSTEN  /f /w:TUNGSTEN.lst 
dfm1s URANIA  /f /w:URANIA.lst 
dfm1s Y-BA-CUO  /f /w:Y-BA-CUO.lst 
dfm1s ZIRCONIA  /f /w:ZIRCONIA.lst 
dpark

