fixpar ALPHA-FE.ppp ALPHA-FE.p 
fixpar ALPHA-TI.ppp ALPHA-TI.p 
fixpar ALPHA-ZR.ppp ALPHA-ZR.p 
fixpar ALUMINA.ppp ALUMINA.p 
fixpar BETA-TI.ppp BETA-TI.p 
fixpar BETA-ZR.ppp BETA-ZR.p 
fixpar COPPER.ppp COPPER.p 
fixpar LEAD.ppp LEAD.p 
fixpar MAGNESIA.ppp MAGNESIA.p 
fixpar MAR-M200.ppp MAR-M200.p 
fixpar MOLYBDM.ppp MOLYBDM.p 
fixpar NICKEL.ppp NICKEL.p 
fixpar ROCKSALT.ppp ROCKSALT.p 
fixpar SILVER.ppp SILVER.p 
fixpar SS-304.ppp SS-304.p 
fixpar SS-316.ppp SS-316.p 
fixpar T-STEEL.ppp T-STEEL.p 
fixpar TIN.ppp TIN.p 
fixpar TUNGSTEN.ppp TUNGSTEN.p 
fixpar URANIA.ppp URANIA.p 
fixpar Y-BA-CUO.ppp Y-BA-CUO.p 
fixpar ZIRCONIA.ppp ZIRCONIA.p 
rem fixpar mo-test.ppp mo-test.p 

