fixvbl ALPHA-FE.vvv ALPHA-FE.v 
fixvbl ALPHA-TI.vvv ALPHA-TI.v 
fixvbl ALPHA-ZR.vvv ALPHA-ZR.v 
fixvbl ALUMINA.vvv ALUMINA.v 
fixvbl BETA-TI.vvv BETA-TI.v 
fixvbl BETA-ZR.vvv BETA-ZR.v 
fixvbl COPPER.vvv COPPER.v 
fixvbl LEAD.vvv LEAD.v 
fixvbl MAGNESIA.vvv MAGNESIA.v 
fixvbl MAR-M200.vvv MAR-M200.v 
fixvbl MOLYBDM.vvv MOLYBDM.v 
fixvbl NICKEL.vvv NICKEL.v 
fixvbl ROCKSALT.vvv ROCKSALT.v 
fixvbl SILVER.vvv SILVER.v 
fixvbl SS-304.vvv SS-304.v 
fixvbl SS-316.vvv SS-316.v 
fixvbl T-STEEL.vvv T-STEEL.v 
fixvbl TIN.vvv TIN.v 
fixvbl TUNGSTEN.vvv TUNGSTEN.v 
fixvbl URANIA.vvv URANIA.v 
fixvbl Y-BA-CUO.vvv Y-BA-CUO.v 
fixvbl ZIRCONIA.vvv ZIRCONIA.v 
rem fixvbl mo-test.vvv mo-test.v 

